### PR TITLE
Scpi gpib can

### PR DESCRIPTION
**Pull request by jackparmer**
### Description

- [ ] I've included a concise description of what each node does

### Styleguide

- [ ] My node adheres to the [styleguide](https://github.com/flojoy-io/nodes/blob/main/node_styleguide.md) for Flojoy nodes

### Docs

- [ ] I've submitted a PR for a documentation page for the new node(s) that contains usage examples (see docs.flojoy.io)

### Testing

- [ ] This PR includes a unit test ([example here](https://github.com/flojoy-io/nodes/blob/c28808f2d0aec8f116cdb3fccb46c4f5256574e9/TRANSFORMERS/ARITHMETIC/ADD/ADD_test_.py) and/or ideally a screenshot of the node's output on an example app.

### CODE REVIEW

**Review by dstrande — COMMENTED** [review]
Look good.

For instrument nodes we should probably include app,jpeg and output.jpeg since they won't be autogenned? 

Also make sure to format with Black.

**Comment by jackparmer** [comment]
> For instrument nodes we should probably include app,jpeg and output.jpeg since they won't be autogenerated?

Do these get automatically mirrored from the nodes repo to the docs repo?

**Comment by dstrande** [comment]
I'm not sure how it works now. For instruments nodes I'm guessing not.

**Comment by dstrande** [comment]
If you generate them and make the example.md files I'll put them in the docs

**Review by itsjoeoui — APPROVED** [review]
lgtm

**Pull request merged**
