### PR TITLE
-I/O Reorganization 

### PR DESCRIPTION
**Pull request by Angchau**
### Description
Reorganize all I/O nodes according to JACK baseline. 
Added new nodes for Analog sensors and modified old nodes such as Phidget22 and LabJack U3

### Docs
I'll submit another PR in the studio and the DOC repo related to this one.

### CODE REVIEW

**Comment by dstrande** [comment]
Can you fix the MOCK test? Not sure why it can't find the module:

`FAILED IO/INSTRUMENTS/MOCK/WEINSCHEL8320/MOCK_WEINSCHEL8320_test_.py::test_MOCK_WEINSCHEL8320 - ModuleNotFoundError: No module named 'MOCK_WEINSCHEL8320'`

**Comment by dstrande** [comment]
There's quite a few 'empty' nodes here like:

```
flojoy()
def STM32(default: Optional[DataContainer] = None) -> OrderedPair:
    return OrderedPair()
```

Do we really want to include all these that don't actually do anything?

**Review by dstrande — CHANGES_REQUESTED** [review]
Try and fix the MOCK node test failing. Run Black formatter.

Also I don't think we should have all the placeholder nodes until they're actually ready. Unless @jackparmer disagrees.

**Comment by Angchau** [comment]
> Try and fix the MOCK node test failing. Run Black formatter.
> 
> Also I don't think we should have all the placeholder nodes until they're actually ready. Unless @jackparmer disagrees.

Okay sure For the Mock node, I know why it fails. Concerning the empty nodes, I was not sure what to do. We'll wait to see what @jackparmer says about this

**Comment by Angchau** [comment]
Requested Changes addressed, except for empty nodes!

**Review by dstrande — APPROVED** [review]
LGTM

**Pull request merged**
