### PR TITLE
Pytests for file system nodes

### PR DESCRIPTION
**Pull request by Jin1L**
### Testing
- [x] EXTRACT_COLUMNS 
- [x] OPEN_IMAGE
- [x] OPEN_PARQUET
- [x] READ_CSV
- [x] READ_S3 
- [x] LOCAL_FILE 
- [x] OPEN_MATLAB

### CODE REVIEW

**Comment by Roulbac** [comment]
@Jin1L I recommend https://github.com/getmoto/moto to mock the S3 bucket

**Comment by Roulbac** [comment]
`keyring` is very problematic on Linux (for `READ_S3` node), see https://github.com/jaraco/keyring#installation---linux
Even though it's mocked out for these tests, it will probably not work in a real setting on Linux @Jin1L

**Comment by Roulbac** [comment]
Hey @Jin1L should we worry about `keyring` on Linux?

**Comment by Jin1L** [comment]
> 

Hmm yeah I think we should find alternative to ```keyring```. I'll discuss with Joey and let you know more about it!

**Pull request merged**
